services:
  postgres:
    image: postgres:16-alpine
    container_name: dashboard_generator_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashboard_generator
    ports:
      - "5434:5432"
    volumes:
      - dashboard_generator_pgdata:/var/lib/postgresql/data

volumes:
  dashboard_generator_pgdata: